// Demo seed data for SmartPOS Mobile Store.
// All records created from this file are demo/sample data.

export type SeedVariant = {
  color: string;
  storage?: string;
  ram?: string;
  price: number;
  stock: number;
  lowStockThreshold?: number;
};

export type SeedProduct = {
  name: string;
  slug: string;
  brand: string;
  sku: string;
  category: string; // category slug
  description: string;
  shortDescription: string;
  basePrice: number;
  compareAtPrice?: number;
  display?: string;
  camera?: string;
  battery?: string;
  warranty?: string;
  specs: Record<string, string>;
  featured?: boolean;
  isNew?: boolean;
  soldCount: number;
  images?: string[];
  variants: SeedVariant[];
};

// Phone products ship with three illustrations, everything else with two.
const PHONE_SLUGS = new Set([
  "samsung-galaxy-a16",
  "samsung-galaxy-a25",
  "samsung-galaxy-a35",
  "apple-iphone-13",
  "apple-iphone-14",
  "apple-iphone-15",
  "redmi-note-13",
  "redmi-note-13-pro",
  "oneplus-nord-ce-4",
  "oneplus-nord-4",
  "google-pixel-8a",
  "google-pixel-8",
]);

const PRODUCT_IMAGES: Record<string, string> = {
  "samsung-galaxy-a16": "jpg",
  "samsung-galaxy-a25": "jpg",
  "samsung-galaxy-a35": "png",
  "apple-iphone-13": "jpg",
  "apple-iphone-14": "jpg",
  "apple-iphone-15": "jpg",
  "redmi-note-13": "png",
  "redmi-note-13-pro": "png",
  "oneplus-nord-ce-4": "png",
  "oneplus-nord-4": "png",
  "google-pixel-8a": "jpg",
  "google-pixel-8": "jpg",
  "anker-soundcore-p40i-earbuds": "png",
  "redmi-buds-5": "png",
  "anker-soundcore-h30i-headphones": "jpg",
  "anker-33w-usb-c-charger": "png",
  "anker-usb-c-cable": "png",
  "anker-20w-car-charger": "png",
  "anker-powercore-20000": "png",
  "spigen-rugged-armor-cover": "jpg",
  "spigen-iphone-15-silicone-cover": "jpg",
  "spigen-tempered-glass": "jpg",
  "xiaomi-smart-band-8": "png",
  "jbl-go-4-speaker": "jpg",
};

export function productImagePaths(slug: string): string[] {
  const ext = PRODUCT_IMAGES[slug] ?? "jpg";
  return [`/images/products/${slug}.${ext}`];
}

export const categories = [
  {
    name: "Smartphones",
    slug: "smartphones",
    description:
      "Latest 5G smartphones from Samsung, Apple, Xiaomi, OnePlus and Google with official warranty.",
    icon: "Smartphone",
    sortOrder: 1,
  },
  {
    name: "Earbuds & Headphones",
    slug: "audio",
    description:
      "Wireless earbuds, over-ear headphones and audio accessories with active noise cancellation.",
    icon: "Headphones",
    sortOrder: 2,
  },
  {
    name: "Chargers & Cables",
    slug: "charging",
    description:
      "Fast chargers, USB-C cables and car chargers to keep your devices powered all day.",
    icon: "Plug",
    sortOrder: 3,
  },
  {
    name: "Power Banks",
    slug: "power-banks",
    description:
      "High-capacity portable power banks with fast charging and multiple output ports.",
    icon: "BatteryCharging",
    sortOrder: 4,
  },
  {
    name: "Cases & Covers",
    slug: "covers",
    description:
      "Protective phone cases and covers with shock absorption and a premium finish.",
    icon: "Shield",
    sortOrder: 5,
  },
  {
    name: "Screen Protectors",
    slug: "screen-protectors",
    description:
      "9H tempered glass screen protectors with full coverage and oleophobic coating.",
    icon: "ShieldCheck",
    sortOrder: 6,
  },
  {
    name: "Smart Watches",
    slug: "smart-watches",
    description:
      "Fitness-focused smart watches with AMOLED displays, SpO2 and long battery life.",
    icon: "Watch",
    sortOrder: 7,
  },
  {
    name: "Bluetooth Speakers",
    slug: "speakers",
    description:
      "Portable Bluetooth speakers with rich bass, water resistance and long playtime.",
    icon: "Speaker",
    sortOrder: 8,
  },
];

export const products: SeedProduct[] = [
  {
    name: "Samsung Galaxy A16",
    slug: "samsung-galaxy-a16",
    brand: "Samsung",
    sku: "SAM-A16-128",
    category: "smartphones",
    description:
      "The Samsung Galaxy A16 pairs a large 6.7-inch Super AMOLED display with a dependable 5000mAh battery and a versatile 50MP main camera. With 6GB of RAM and 128GB of expandable storage, it is a solid everyday phone for work, streaming and photography.",
    shortDescription: "6.7\" AMOLED · 50MP camera · 5000mAh battery",
    basePrice: 54999,
    compareAtPrice: 59999,
    display: "6.7-inch Super AMOLED, 90Hz",
    camera: "50MP main + 5MP ultrawide + 2MP macro",
    battery: "5000mAh, 25W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Exynos 1280",
      "Operating System": "Android 14, One UI 6",
      Storage: "128GB (expandable up to 1.5TB)",
      RAM: "6GB",
      Display: "6.7-inch Super AMOLED, 90Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "13MP",
      Battery: "5000mAh",
      SIM: "Dual SIM (Nano + eSIM)",
      Security: "Side-mounted fingerprint, Face unlock",
    },
    featured: true,
    soldCount: 142,
    variants: [
      { color: "Black", storage: "128GB", ram: "6GB", price: 54999, stock: 10 },
      { color: "Blue", storage: "128GB", ram: "6GB", price: 54999, stock: 8 },
    ],
  },
  {
    name: "Samsung Galaxy A25",
    slug: "samsung-galaxy-a25",
    brand: "Samsung",
    sku: "SAM-A25-128",
    category: "smartphones",
    description:
      "The Galaxy A25 5G delivers smooth performance with 8GB of RAM and a vivid 6.5-inch Super AMOLED display. A 50MP camera with optical image stabilisation and a 5000mAh battery make it a well-rounded mid-range choice.",
    shortDescription: "6.5\" AMOLED · 8GB RAM · 5G",
    basePrice: 69999,
    compareAtPrice: 74999,
    display: "6.5-inch Super AMOLED, 120Hz",
    camera: "50MP OIS main + 8MP ultrawide + 2MP macro",
    battery: "5000mAh, 25W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Exynos 1280",
      "Operating System": "Android 14, One UI 6",
      Storage: "128GB",
      RAM: "8GB",
      Display: "6.5-inch Super AMOLED, 120Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "13MP",
      Battery: "5000mAh",
      SIM: "Dual SIM",
      "5G": "Yes",
    },
    featured: true,
    soldCount: 118,
    variants: [
      { color: "Blue", storage: "128GB", ram: "8GB", price: 69999, stock: 7 },
      { color: "Black", storage: "128GB", ram: "8GB", price: 69999, stock: 5 },
    ],
  },
  {
    name: "Samsung Galaxy A35",
    slug: "samsung-galaxy-a35",
    brand: "Samsung",
    sku: "SAM-A35-256",
    category: "smartphones",
    description:
      "The Galaxy A35 5G brings a premium glass finish, a 6.6-inch 120Hz Super AMOLED screen and 256GB of storage. The 50MP OIS camera captures sharp photos day and night, backed by a 5000mAh battery.",
    shortDescription: "6.6\" AMOLED · 256GB · 50MP OIS",
    basePrice: 104999,
    compareAtPrice: 112999,
    display: "6.6-inch Super AMOLED, 120Hz",
    camera: "50MP OIS main + 8MP ultrawide + 5MP macro",
    battery: "5000mAh, 25W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Exynos 1380",
      "Operating System": "Android 14, One UI 6.1",
      Storage: "256GB",
      RAM: "8GB",
      Display: "6.6-inch Super AMOLED, 120Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "13MP",
      Battery: "5000mAh",
      Protection: "IP67 water and dust resistant",
      "5G": "Yes",
    },
    featured: true,
    isNew: true,
    soldCount: 76,
    variants: [
      { color: "Black", storage: "256GB", ram: "8GB", price: 104999, stock: 6 },
      { color: "Blue", storage: "256GB", ram: "8GB", price: 104999, stock: 4 },
    ],
  },
  {
    name: "Apple iPhone 13",
    slug: "apple-iphone-13",
    brand: "Apple",
    sku: "APP-IP13-128",
    category: "smartphones",
    description:
      "iPhone 13 features the A15 Bionic chip, a bright 6.1-inch Super Retina XDR display and an advanced dual-camera system with Cinematic mode. A reliable choice with excellent resale value and long-term software support.",
    shortDescription: "6.1\" Super Retina XDR · A15 Bionic · Dual camera",
    basePrice: 149999,
    compareAtPrice: 159999,
    display: "6.1-inch Super Retina XDR, 60Hz",
    camera: "12MP dual camera with Night mode",
    battery: "Up to 19 hours video playback",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Apple A15 Bionic",
      "Operating System": "iOS 17",
      Storage: "128GB",
      Display: "6.1-inch Super Retina XDR",
      "Main Camera": "12MP wide + 12MP ultrawide",
      "Front Camera": "12MP TrueDepth",
      Battery: "3240mAh",
      Charging: "Lightning, MagSafe compatible",
      Protection: "IP68",
    },
    featured: true,
    soldCount: 98,
    variants: [
      { color: "Black", storage: "128GB", price: 149999, stock: 3 },
      { color: "Blue", storage: "128GB", price: 149999, stock: 3 },
      { color: "White", storage: "128GB", price: 149999, stock: 2 },
    ],
  },
  {
    name: "Apple iPhone 14",
    slug: "apple-iphone-14",
    brand: "Apple",
    sku: "APP-IP14-128",
    category: "smartphones",
    description:
      "iPhone 14 adds crash detection, Emergency SOS via satellite and an improved dual-camera with Photonic Engine for dramatically better low-light photos. Powered by the A15 Bionic chip with a 6-core GPU.",
    shortDescription: "6.1\" Super Retina XDR · Photonic Engine",
    basePrice: 179999,
    compareAtPrice: 189999,
    display: "6.1-inch Super Retina XDR, 60Hz",
    camera: "12MP dual camera, Photonic Engine",
    battery: "Up to 20 hours video playback",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Apple A15 Bionic (5-core GPU)",
      "Operating System": "iOS 17",
      Storage: "128GB",
      Display: "6.1-inch Super Retina XDR",
      "Main Camera": "12MP wide + 12MP ultrawide",
      "Front Camera": "12MP TrueDepth autofocus",
      Battery: "3279mAh",
      Safety: "Crash Detection, Emergency SOS",
      Protection: "IP68",
    },
    soldCount: 71,
    variants: [
      { color: "Midnight", storage: "128GB", price: 179999, stock: 3 },
      { color: "Blue", storage: "128GB", price: 179999, stock: 2 },
      { color: "Starlight", storage: "128GB", price: 179999, stock: 2 },
    ],
  },
  {
    name: "Apple iPhone 15",
    slug: "apple-iphone-15",
    brand: "Apple",
    sku: "APP-IP15-128",
    category: "smartphones",
    description:
      "iPhone 15 introduces the Dynamic Island, a 48MP main camera with 2x telephoto and USB-C. The A16 Bionic chip and a colour-infused glass back make it one of the most refined standard iPhones yet.",
    shortDescription: "6.1\" Super Retina XDR · 48MP · Dynamic Island",
    basePrice: 219999,
    compareAtPrice: 229999,
    display: "6.1-inch Super Retina XDR, 60Hz",
    camera: "48MP main + 12MP ultrawide",
    battery: "Up to 20 hours video playback",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Apple A16 Bionic",
      "Operating System": "iOS 17",
      Storage: "128GB",
      Display: "6.1-inch Super Retina XDR",
      "Main Camera": "48MP main + 12MP ultrawide",
      "Front Camera": "12MP TrueDepth",
      Battery: "3349mAh",
      Charging: "USB-C, MagSafe",
      Safety: "Dynamic Island, Crash Detection",
    },
    featured: true,
    isNew: true,
    soldCount: 64,
    variants: [
      { color: "Black", storage: "128GB", price: 219999, stock: 2 },
      { color: "Blue", storage: "128GB", price: 219999, stock: 2 },
      { color: "Green", storage: "128GB", price: 219999, stock: 2 },
    ],
  },
  {
    name: "Xiaomi Redmi Note 13",
    slug: "redmi-note-13",
    brand: "Xiaomi",
    sku: "RED-N13-128",
    category: "smartphones",
    description:
      "The Redmi Note 13 offers a 108MP camera, a 6.67-inch AMOLED display and a 5000mAh battery at an accessible price. A dependable budget smartphone for photography and all-day use.",
    shortDescription: "6.67\" AMOLED · 108MP · 5000mAh",
    basePrice: 54999,
    compareAtPrice: 59999,
    display: "6.67-inch AMOLED, 120Hz",
    camera: "108MP main + 8MP ultrawide + 2MP macro",
    battery: "5000mAh, 33W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 685",
      "Operating System": "Android 13, MIUI 14",
      Storage: "128GB",
      RAM: "6GB",
      Display: "6.67-inch AMOLED, 120Hz",
      "Main Camera": "108MP",
      "Front Camera": "16MP",
      Battery: "5000mAh",
      Protection: "IP54",
    },
    soldCount: 205,
    variants: [
      { color: "Midnight Black", storage: "128GB", ram: "6GB", price: 54999, stock: 14 },
      { color: "Ocean Blue", storage: "128GB", ram: "6GB", price: 54999, stock: 8 },
    ],
  },
  {
    name: "Xiaomi Redmi Note 13 Pro",
    slug: "redmi-note-13-pro",
    brand: "Xiaomi",
    sku: "RED-N13P-256",
    category: "smartphones",
    description:
      "Redmi Note 13 Pro upgrades to a 200MP camera, a Snapdragon 7s Gen 2 processor and 67W turbo charging. A 6.67-inch 1.5K AMOLED display rounds out a remarkable value package.",
    shortDescription: "6.67\" 1.5K AMOLED · 200MP · 67W",
    basePrice: 84999,
    compareAtPrice: 89999,
    display: "6.67-inch 1.5K AMOLED, 120Hz",
    camera: "200MP OIS + 8MP ultrawide + 2MP macro",
    battery: "5100mAh, 67W turbo charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 7s Gen 2",
      "Operating System": "Android 13, MIUI 14",
      Storage: "256GB",
      RAM: "8GB",
      Display: "6.67-inch 1.5K AMOLED",
      "Main Camera": "200MP OIS",
      "Front Camera": "16MP",
      Battery: "5100mAh",
      Protection: "IP54",
    },
    isNew: true,
    soldCount: 133,
    variants: [
      { color: "Midnight Black", storage: "256GB", ram: "8GB", price: 84999, stock: 9 },
      { color: "Ocean Blue", storage: "256GB", ram: "8GB", price: 84999, stock: 5 },
    ],
  },
  {
    name: "OnePlus Nord CE 4",
    slug: "oneplus-nord-ce-4",
    brand: "OnePlus",
    sku: "ONE-NCE4-128",
    category: "smartphones",
    description:
      "The OnePlus Nord CE 4 combines the Snapdragon 7 Gen 3 with 100W SUPERVOOC charging and a 5500mAh battery. A 6.7-inch AMOLED display and clean OxygenOS experience make it an excellent value flagship.",
    shortDescription: "6.7\" AMOLED · 100W charging · 5500mAh",
    basePrice: 114999,
    compareAtPrice: 124999,
    display: "6.7-inch AMOLED, 120Hz",
    camera: "50MP OIS main + 8MP ultrawide",
    battery: "5500mAh, 100W SUPERVOOC",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 7 Gen 3",
      "Operating System": "Android 14, OxygenOS 14",
      Storage: "128GB",
      RAM: "8GB",
      Display: "6.7-inch AMOLED, 120Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "16MP",
      Battery: "5500mAh",
      Charging: "100W SUPERVOOC",
    },
    soldCount: 58,
    variants: [
      { color: "Black", storage: "128GB", ram: "8GB", price: 114999, stock: 5 },
      { color: "Blue", storage: "128GB", ram: "8GB", price: 114999, stock: 4 },
    ],
  },
  {
    name: "OnePlus Nord 4",
    slug: "oneplus-nord-4",
    brand: "OnePlus",
    sku: "ONE-N4-256",
    category: "smartphones",
    description:
      "The OnePlus Nord 4 brings a premium aluminium unibody, Snapdragon 7+ Gen 3 performance and 12GB of RAM. 100W SUPERVOOC charging refills the 5500mAh battery in minutes.",
    shortDescription: "6.74\" AMOLED · 12GB RAM · 100W",
    basePrice: 149999,
    compareAtPrice: 159999,
    display: "6.74-inch AMOLED, 120Hz",
    camera: "50MP OIS main + 8MP ultrawide",
    battery: "5500mAh, 100W SUPERVOOC",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 7+ Gen 3",
      "Operating System": "Android 14, OxygenOS 14.1",
      Storage: "256GB",
      RAM: "12GB",
      Display: "6.74-inch AMOLED, 120Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "16MP",
      Battery: "5500mAh",
      Build: "Aluminium unibody",
    },
    isNew: true,
    soldCount: 41,
    variants: [
      { color: "Black", storage: "256GB", ram: "12GB", price: 149999, stock: 4 },
      { color: "Blue", storage: "256GB", ram: "12GB", price: 149999, stock: 3 },
    ],
  },
  {
    name: "Google Pixel 8a",
    slug: "google-pixel-8a",
    brand: "Google",
    sku: "GOO-P8A-128",
    category: "smartphones",
    description:
      "Pixel 8a brings Google Tensor G3 and the best-in-class Pixel camera to a more affordable price. Seven years of OS and security updates, plus Gemini AI features and a bright 120Hz Actua display.",
    shortDescription: "6.1\" Actua display · Tensor G3 · 7 years updates",
    basePrice: 149999,
    compareAtPrice: 159999,
    display: "6.1-inch Actua OLED, 120Hz",
    camera: "64MP OIS main + 13MP ultrawide",
    battery: "4492mAh, 18W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Google Tensor G3",
      "Operating System": "Android 14",
      Storage: "128GB",
      RAM: "8GB",
      Display: "6.1-inch Actua OLED, 120Hz",
      "Main Camera": "64MP OIS",
      "Front Camera": "13MP",
      Battery: "4492mAh",
      Updates: "7 years of OS and security updates",
    },
    featured: true,
    soldCount: 47,
    variants: [
      { color: "Black", storage: "128GB", ram: "8GB", price: 149999, stock: 4 },
      { color: "Blue", storage: "128GB", ram: "8GB", price: 149999, stock: 4 },
    ],
  },
  {
    name: "Google Pixel 8",
    slug: "google-pixel-8",
    brand: "Google",
    sku: "GOO-P8-256",
    category: "smartphones",
    description:
      "Pixel 8 delivers the full Google AI camera experience with a 50MP main sensor, Magic Editor and Best Take. The 6.2-inch 120Hz display and Tensor G3 keep everything fast and fluid.",
    shortDescription: "6.2\" OLED · 50MP · Pure Android",
    basePrice: 199999,
    compareAtPrice: 209999,
    display: "6.2-inch OLED, 120Hz",
    camera: "50MP OIS main + 12MP ultrawide",
    battery: "4575mAh, 27W fast charging",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Google Tensor G3",
      "Operating System": "Android 14",
      Storage: "256GB",
      RAM: "8GB",
      Display: "6.2-inch OLED, 120Hz",
      "Main Camera": "50MP OIS",
      "Front Camera": "10.5MP",
      Battery: "4575mAh",
      Updates: "7 years of OS and security updates",
    },
    soldCount: 29,
    variants: [
      { color: "Black", storage: "256GB", ram: "8GB", price: 199999, stock: 3 },
      { color: "Blue", storage: "256GB", ram: "8GB", price: 199999, stock: 2 },
    ],
  },
  {
    name: "Anker Soundcore P40i Wireless Earbuds",
    slug: "anker-soundcore-p40i-earbuds",
    brand: "Anker",
    sku: "ACC-EAR-P40I",
    category: "audio",
    description:
      "Soundcore P40i true wireless earbuds feature adaptive active noise cancellation, 60 hours of total playtime with the charging case and a bass-up driver for punchy sound. IPX5 water resistance makes them ideal for workouts.",
    shortDescription: "Bluetooth 5.3 · ANC · 60h total playtime",
    basePrice: 12999,
    compareAtPrice: 14999,
    warranty: "1 Year Warranty",
    specs: {
      Bluetooth: "Bluetooth 5.3",
      "Noise Cancellation": "Adaptive ANC",
      "Playtime": "12h + 48h with case",
      Charging: "USB-C, wireless charging",
      "Water Resistance": "IPX5",
      Driver: "11mm dynamic driver",
      Microphones: "6 mics with AI call noise reduction",
    },
    featured: true,
    soldCount: 176,
    variants: [
      { color: "Black", price: 12999, stock: 18 },
      { color: "White", price: 12999, stock: 12 },
    ],
  },
  {
    name: "Xiaomi Redmi Buds 5",
    slug: "redmi-buds-5",
    brand: "Xiaomi",
    sku: "ACC-EAR-RB5",
    category: "audio",
    description:
      "Redmi Buds 5 deliver 46dB hybrid noise cancellation, 40 hours of total battery life and a 12.4mm titanium driver for rich audio. A lightweight and affordable everyday pair of earbuds.",
    shortDescription: "Bluetooth 5.3 · 46dB ANC · 40h playtime",
    basePrice: 8999,
    compareAtPrice: 9999,
    warranty: "1 Year Warranty",
    specs: {
      Bluetooth: "Bluetooth 5.3",
      "Noise Cancellation": "46dB hybrid ANC",
      "Playtime": "10h + 30h with case",
      Charging: "USB-C",
      "Water Resistance": "IP54",
      Driver: "12.4mm titanium",
    },
    soldCount: 154,
    variants: [{ color: "White", price: 8999, stock: 15 }, { color: "Black", price: 8999, stock: 10 }],
  },
  {
    name: "Anker 33W USB-C Fast Charger",
    slug: "anker-33w-usb-c-charger",
    brand: "Anker",
    sku: "ACC-CHG-33W",
    category: "charging",
    description:
      "A compact 33W GaN USB-C wall charger with PowerIQ 3.0 technology. Charges smartphones, tablets and earbuds quickly while staying cool and travel-friendly.",
    shortDescription: "33W GaN · USB-C · PowerIQ 3.0",
    basePrice: 3499,
    compareAtPrice: 3999,
    warranty: "18 Month Warranty",
    specs: {
      Output: "33W USB-C",
      Technology: "GaN II, PowerIQ 3.0",
      Compatibility: "iPhone, Samsung, Xiaomi, tablets",
      Safety: "MultiProtect safety system",
      Plug: "Foldable, travel friendly",
    },
    soldCount: 240,
    variants: [{ color: "White", price: 3499, stock: 40 }],
  },
  {
    name: "Anker PowerCore 20000mAh Power Bank",
    slug: "anker-powercore-20000",
    brand: "Anker",
    sku: "ACC-PWB-20K",
    category: "power-banks",
    description:
      "A 20,000mAh power bank with two USB-A ports and one USB-C port. PowerIQ and VoltageBoost technologies deliver the fastest possible charge for any device, with enough capacity for multiple full charges.",
    shortDescription: "20000mAh · USB-C + dual USB-A · PowerIQ",
    basePrice: 5999,
    compareAtPrice: 6999,
    warranty: "18 Month Warranty",
    specs: {
      Capacity: "20000mAh",
      Output: "USB-C 20W + 2x USB-A 12W",
      Input: "USB-C",
      Technology: "PowerIQ, VoltageBoost",
      Recharge: "Full recharge in 4.5 hours",
      Safety: "MultiProtect safety system",
    },
    featured: true,
    soldCount: 189,
    variants: [{ color: "Black", price: 5999, stock: 16 }, { color: "Blue", price: 5999, stock: 10 }],
  },
  {
    name: "Spigen Rugged Armor Mobile Cover",
    slug: "spigen-rugged-armor-cover",
    brand: "Spigen",
    sku: "ACC-CVR-RUG",
    category: "covers",
    description:
      "The Spigen Rugged Armor case uses flexible TPU with Air Cushion Technology to protect your phone from drops and impacts. The matte carbon fibre finish resists fingerprints and adds a premium grip.",
    shortDescription: "Shock-absorbing TPU · Air Cushion Technology",
    basePrice: 1499,
    compareAtPrice: 1999,
    warranty: "6 Month Warranty",
    specs: {
      Material: "Flexible TPU",
      Protection: "Air Cushion Technology drop protection",
      Finish: "Matte carbon fibre",
      Compatibility: "Multiple flagship models",
      Features: "Raised camera and screen lip",
    },
    soldCount: 320,
    variants: [
      { color: "Black", price: 1499, stock: 30 },
      { color: "Blue", price: 1499, stock: 20 },
    ],
  },
  {
    name: "Spigen Tempered Glass Screen Protector",
    slug: "spigen-tempered-glass",
    brand: "Spigen",
    sku: "ACC-SPR-TG",
    category: "screen-protectors",
    description:
      "9H hardness tempered glass with full edge-to-edge coverage and an oleophobic coating that repels oil and fingerprints. Includes an easy alignment installation kit.",
    shortDescription: "9H tempered glass · Oleophobic coating",
    basePrice: 999,
    compareAtPrice: 1499,
    warranty: "3 Month Warranty",
    specs: {
      Material: "9H tempered glass",
      Coating: "Oleophobic, anti-fingerprint",
      Coverage: "Full edge-to-edge",
      Thickness: "0.33mm",
      "Case Friendly": "Yes",
      Installation: "Alignment frame included",
    },
    soldCount: 410,
    variants: [{ color: "Clear", price: 999, stock: 60 }],
  },
  {
    name: "Xiaomi Smart Band 8",
    slug: "xiaomi-smart-band-8",
    brand: "Xiaomi",
    sku: "ACC-WCH-B8",
    category: "smart-watches",
    description:
      "The Xiaomi Smart Band 8 features a 1.62-inch AMOLED display, 16-day battery life and over 150 workout modes. It tracks heart rate, blood oxygen, sleep and stress around the clock.",
    shortDescription: "1.62\" AMOLED · 16-day battery · 150+ workout modes",
    basePrice: 9999,
    compareAtPrice: 11999,
    warranty: "1 Year Warranty",
    specs: {
      Display: "1.62-inch AMOLED",
      Battery: "Up to 16 days",
      Sensors: "Heart rate, SpO2, accelerometer",
      "Workout Modes": "150+",
      "Water Resistance": "5ATM",
      Connectivity: "Bluetooth 5.1",
      Compatibility: "Android and iOS",
    },
    featured: true,
    soldCount: 112,
    variants: [{ color: "Black", price: 9999, stock: 10 }, { color: "Gold", price: 10499, stock: 8 }],
  },
  {
    name: "JBL Go 4 Bluetooth Speaker",
    slug: "jbl-go-4-speaker",
    brand: "JBL",
    sku: "ACC-SPK-GO4",
    category: "speakers",
    description:
      "The JBL Go 4 is an ultra-portable Bluetooth speaker with bold JBL Pro Sound, 7 hours of playtime and an IP67 waterproof and dustproof rating. Pair two speakers for stereo sound.",
    shortDescription: "Bluetooth 5.3 · IP67 · 7h playtime",
    basePrice: 6999,
    compareAtPrice: 7999,
    warranty: "1 Year Warranty",
    specs: {
      Bluetooth: "Bluetooth 5.3",
      Battery: "7 hours playtime",
      "Water Resistance": "IP67 waterproof and dustproof",
      Features: "JBL Pro Sound, PartyBoost",
      Charging: "USB-C",
      Weight: "190g",
    },
    soldCount: 143,
    variants: [
      { color: "Black", price: 6999, stock: 12 },
      { color: "Blue", price: 6999, stock: 8 },
    ],
  },
  {
    name: "Anker USB-C to USB-C Cable 1.2m",
    slug: "anker-usb-c-cable",
    brand: "Anker",
    sku: "ACC-CBL-USBC",
    category: "charging",
    description:
      "A durable 1.2m USB-C to USB-C cable supporting up to 60W Power Delivery fast charging and 480Mbps data transfer. The reinforced nylon braid withstands over 12,000 bends.",
    shortDescription: "60W PD · Nylon braided · 1.2m",
    basePrice: 1299,
    compareAtPrice: 1699,
    warranty: "18 Month Warranty",
    specs: {
      Length: "1.2 metres",
      Power: "Up to 60W Power Delivery",
      Data: "480Mbps",
      Material: "Reinforced nylon braid",
      Connectors: "USB-C to USB-C",
      Durability: "12,000+ bend lifespan",
    },
    soldCount: 365,
    variants: [{ color: "Black", price: 1299, stock: 35 }, { color: "White", price: 1299, stock: 20 }],
  },
  {
    name: "Anker 20W USB-C Car Charger",
    slug: "anker-20w-car-charger",
    brand: "Anker",
    sku: "ACC-CHG-CAR20",
    category: "charging",
    description:
      "A compact 20W car charger with USB-C Power Delivery and an additional USB-A port. Charge two devices at once during your commute with full-speed fast charging.",
    shortDescription: "20W USB-C PD + USB-A · Dual port",
    basePrice: 2499,
    warranty: "18 Month Warranty",
    specs: {
      Output: "20W USB-C + 12W USB-A",
      Input: "12V / 24V car socket",
      Technology: "PowerIQ, Power Delivery",
      Safety: "MultiProtect safety system",
      Build: "Compact metal body",
    },
    soldCount: 158,
    variants: [{ color: "Black", price: 2499, stock: 35 }],
  },
  {
    name: "Anker Soundcore H30i Headphones",
    slug: "anker-soundcore-h30i-headphones",
    brand: "Anker",
    sku: "ACC-HPH-H30I",
    category: "audio",
    description:
      "Soundcore H30i over-ear headphones deliver 70 hours of playtime, custom 40mm drivers and BassUp technology. Lightweight with a foldable design for comfortable all-day listening.",
    shortDescription: "Over-ear · 70h playtime · BassUp",
    basePrice: 3999,
    compareAtPrice: 4999,
    warranty: "18 Month Warranty",
    specs: {
      Type: "Over-ear wireless",
      Battery: "70 hours playtime",
      Driver: "40mm dynamic",
      Technology: "BassUp",
      Connectivity: "Bluetooth 5.3, AUX input",
      Design: "Foldable, lightweight",
    },
    soldCount: 97,
    variants: [{ color: "Black", price: 3999, stock: 14 }, { color: "White", price: 3999, stock: 8 }],
  },
  {
    name: "Spigen iPhone 15 Silicone Cover",
    slug: "spigen-iphone-15-silicone-cover",
    brand: "Spigen",
    sku: "ACC-CVR-IP15",
    category: "covers",
    description:
      "A soft-touch liquid silicone case designed for the iPhone 15 with a microfibre lining and precise cutouts. Raised bezels protect the screen and camera from scratches.",
    shortDescription: "Liquid silicone · Microfibre lining · MagSafe ready",
    basePrice: 1999,
    compareAtPrice: 2499,
    warranty: "6 Month Warranty",
    specs: {
      Material: "Liquid silicone",
      Lining: "Microfibre",
      Compatibility: "iPhone 15",
      Features: "MagSafe compatible, raised bezels",
      Finish: "Soft-touch anti-slip",
    },
    isNew: true,
    soldCount: 88,
    variants: [{ color: "Blue", price: 1999, stock: 16 }, { color: "Black", price: 1999, stock: 12 }],
  },
];

export const customers = [
  { name: "Aisha Khan", email: "aisha.khan@example.com", phone: "+92 300 1234567", city: "Lahore", line1: "House 42, Block C, Gulberg III", postal: "54000" },
  { name: "Bilal Ahmed", email: "bilal.ahmed@example.com", phone: "+92 301 2345678", city: "Karachi", line1: "Flat 12B, Clifton Block 5", postal: "75600" },
  { name: "Sana Malik", email: "sana.malik@example.com", phone: "+92 302 3456789", city: "Islamabad", line1: "House 8, Street 27, F-7/1", postal: "44000" },
  { name: "Usman Tariq", email: "usman.tariq@example.com", phone: "+92 303 4567890", city: "Rawalpindi", line1: "Apartment 5, Bahria Town Phase 4", postal: "46000" },
  { name: "Hina Sheikh", email: "hina.sheikh@example.com", phone: "+92 304 5678901", city: "Faisalabad", line1: "House 19, D Ground, People's Colony", postal: "38000" },
  { name: "Zain Ali", email: "zain.ali@example.com", phone: "+92 305 6789012", city: "Multan", line1: "House 77, Shah Rukn-e-Alam Colony", postal: "60000" },
  { name: "Fatima Noor", email: "fatima.noor@example.com", phone: "+92 306 7890123", city: "Peshawar", line1: "House 3, University Road, Hayatabad", postal: "25000" },
  { name: "Hamza Iqbal", email: "hamza.iqbal@example.com", phone: "+92 307 8901234", city: "Quetta", line1: "House 21, Jinnah Road", postal: "87300" },
  { name: "Mariam Yousaf", email: "mariam.yousaf@example.com", phone: "+92 308 9012345", city: "Lahore", line1: "House 55, DHA Phase 5", postal: "54810" },
  { name: "Ali Raza", email: "ali.raza@example.com", phone: "+92 309 0123456", city: "Karachi", line1: "Flat 9A, Gulshan-e-Iqbal Block 13", postal: "75300" },
  { name: "Noor Fatima", email: "noor.fatima@example.com", phone: "+92 310 1234509", city: "Sialkot", line1: "House 14, Cantt Road", postal: "51310" },
  { name: "Saad Rehman", email: "saad.rehman@example.com", phone: "+92 311 2345610", city: "Hyderabad", line1: "House 6, Latifabad Unit 7", postal: "71000" },
];

export const settings: Record<string, string> = {
  storeName: "SmartPOS Mobile Store",
  storeEmail: "support@smartpos.example",
  storePhone: "+92 21 1234567",
  storeAddress: "Shop 101, Tech Plaza, Main Boulevard, Lahore, Pakistan",
  currency: "PKR",
  taxRate: "0",
  shippingFlatRate: "200",
  freeShippingThreshold: "100000",
  lowStockThreshold: "5",
  posDefaultTaxRate: "0",
};
