import type { Metadata } from "next";
import { Search } from "lucide-react";
import { prisma } from "@/lib/db";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Field, Input, Select } from "@/components/ui/form";
import { Pagination } from "@/components/ui/pagination";
import { EmptyState } from "@/components/ui/misc";
import { AdminPageHeader } from "@/components/admin/page-header";
import { formatNumber } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Email inbox",
  robots: { index: false, follow: false },
};

const PER_PAGE = 15;

export default async function AdminEmailsPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; template?: string; status?: string; page?: string }>;
}) {
  const params = await searchParams;
  const q = params.q?.trim() ?? "";
  const template = params.template ?? "ALL";
  const status = params.status ?? "ALL";
  const page = Math.max(1, Number(params.page ?? 1) || 1);

  const where: Record<string, unknown> = {};
  if (q) where.OR = [{ to: { contains: q } }, { subject: { contains: q } }];
  if (template !== "ALL") where.template = template;
  if (status !== "ALL") where.status = status;

  const [total, emails, templates] = await Promise.all([
    prisma.emailLog.count({ where }),
    prisma.emailLog.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * PER_PAGE,
      take: PER_PAGE,
    }),
    prisma.emailLog.findMany({ distinct: ["template"], select: { template: true } }),
  ]);

  const totalPages = Math.ceil(total / PER_PAGE);

  return (
    <div>
      <AdminPageHeader
        title="Email inbox"
        description="Every transactional email generated by the store. In this demo, emails are simulated and stored here."
      />

      <form className="mb-4 grid gap-3 rounded-xl border border-border bg-surface p-4 sm:grid-cols-[1fr_200px_160px_auto]">
        <Field label="Search" htmlFor="q">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-content-subtle" />
            <Input id="q" name="q" defaultValue={q} placeholder="Recipient or subject" className="pl-9" />
          </div>
        </Field>
        <Field label="Template" htmlFor="template">
          <Select id="template" name="template" defaultValue={template}>
            <option value="ALL">All templates</option>
            {templates.map((row) => (
              <option key={row.template} value={row.template}>{row.template}</option>
            ))}
          </Select>
        </Field>
        <Field label="Status" htmlFor="status">
          <Select id="status" name="status" defaultValue={status}>
            <option value="ALL">All</option>
            <option value="SENT">Sent</option>
            <option value="FAILED">Failed</option>
          </Select>
        </Field>
        <div className="flex items-end">
          <Button type="submit" variant="outline" className="w-full">Filter</Button>
        </div>
      </form>

      <p className="mb-3 text-sm text-content-muted">{formatNumber(total)} messages</p>

      {emails.length === 0 ? (
        <EmptyState title="No emails yet" description="Transactional emails (order confirmations, status updates) will appear here." />
      ) : (
        <ul className="space-y-3">
          {emails.map((email) => (
            <li key={email.id} className="rounded-xl border border-border bg-surface">
              <details className="group">
                <summary className="flex cursor-pointer flex-wrap items-center justify-between gap-2 p-4 [&::-webkit-details-marker]:hidden">
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold text-content">{email.subject}</p>
                    <p className="truncate text-xs text-content-muted">
                      To {email.to} · {email.template}
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    <Badge tone={email.status === "SENT" ? "success" : "danger"}>{email.status}</Badge>
                    <span className="text-xs text-content-subtle">
                      {email.createdAt.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}
                    </span>
                  </div>
                </summary>
                <div className="border-t border-border p-4">
                  <pre className="whitespace-pre-wrap break-words font-sans text-sm text-content-muted">
                    {email.body}
                  </pre>
                  {email.error ? (
                    <p className="mt-3 rounded-lg bg-danger-soft p-3 text-xs text-danger">Error: {email.error}</p>
                  ) : null}
                </div>
              </details>
            </li>
          ))}
        </ul>
      )}

      <div className="mt-6">
        <Pagination currentPage={page} totalPages={totalPages} basePath="/admin/emails" params={{ q, template, status }} />
      </div>
    </div>
  );
}
